export const lgn = {
    "app_greet": "Hey Joe!",
    "edit": "Edit",
    "agriculture" : "Agriculture",
    "agriculture_url" : "agriculture",
    "health" : "Health",
    "health_url" : "health",
    "education" : "Education",
    "education_url" : "education",
    "social_welfare" : "Social Welfare",
    "social_welfare_url" : "social-welfare",
    "e_governance" : "e-Governance",
    "e_governance_url" : "e-governance",
    "energy" : "Energy",
    "energy_url" : "energy",
    "schemes" : "Schemes",
    "schemes_url" : "schemes",
    "aspirational_districts" : "Aspirational Districts",
    "services" : "Services",
    "see_more" : "See more ...",
    "domain" : "Domains",

    "greeting": "Hello World",
    "str_site_name" : "Vikaspedia",
    "login" : "Login",
    "register" : "Register",
    "logout" : "Logout",

    "language" : "Languages",
    "english" : "English",
    "hindi" : "हिंदी",
    "select_language" : "Select Language",
    "skip_to_main_content" : "Skip to main content",
    "search" : "Search",
    "search_within_portal" : "Search Within Portal",
 "search_menu_topics" : "Search in Menu Topics",
    "f_1" : "Moderate Comments",
    "f_2" : "Manage Users",
    "f_3" : "Moderate Members",
    "f_4" : "Moderate Feedbacks",
    "f_5" : "Moderate Chats",
    "f_6" : "My Contributions",
    "f_7" : "Recent Items",
    "f_8" : "Review List",
    "f_9" : "Dashboard",
    "f_10" : "Profile",
    "f_11" : "Insert Keywords",
    "f_12" : "Moderate Links",
    "f_13" : "Page Statstics",
    "f_14" : "MIS Report",
    "f_15" : "Login Attempts",
    "f_16" : "Suggest",
    "f_17" : "News",
    "f_18" : "Events",
    "f_19" : "LogOut",
    "f_21" : "Manage Pages",
    "f_22" :  "All Schemes",
    "f_23" : "Impact Stories",
    "f_24" : "Update Carousel",
    "f_25" : "Manage Roles",
    "f_26" : "Refresh Cache",
    "f_27" : "Register as Contributor",
    "f_28" : "Update Tracking Progress",
    "f_29" : "Login As",
    "login_pageheading" : "User Login",
    "login_email_username" : "Email / Username",
    "login_email_username_placeholder" : "Email / Username",
    "login_password" : "Password",
    "login_password_placeholder" : "Password",
    "login_email_required" : "Email Id is Required",
    "login_email_format" : "Email format must be correct.",
    "login_password_required" : "Password field is Required",
    "login_submit_button" : "Login",
    "login_forgot_password" : "Forgot Your Password?",
    "login_if_forgot_pass" : "If you have forgotten your password",
    "login_send_pass" : "we can send you a new one.",
    "login_new_user" : "New User?",
    "login_if_not_have_account" : "If you do not have an account here, head over to the",
    "login_register_form" : "Registration Form",
    "login_success" : "Welcome, you are loggedin succesfully...",
    "login_user_logged_in" : "User already logged-in",

    "forgotpass_pageheading" : "Forgot Your Password",
    "forgotpass_detail1" : "For security reasons, we store your password encrypted, and hence cannot mail it to you.",
    "forgotpass_detail2" : "If you would like to reset your password, please provide your email address (the one provided by you during the registration process)",
    "forgotpass_detail3" : "A link for resetting your password will be sent to the mentioned email address.",
    "forgotpass_security1" : "There are a few reasons that you might not be able to find the activation email. Please check the following things before you contact us:",
    "forgotpass_security2" : "Please always check your junk/spam folder.",
    "forgotpass_security3" : "Ensure your email id is correct",
    "forgotpass_security4" : "Ensure your inbox is not full.",
    "forgotpass_email" : "Email",
    "forgotpass_email_placeholder" : "Email",
    "forgotpass_email_instruction" : "Enter a email id. Your email id can contain , digits and character '_' . Your mail id must contain '@' symbol. Eg abck@kail.com",
    "forgotpass_submit_button" : "Submit",
    "forgotpass_login_access" : "Login Access   (Click to login)Submit",
    "forgotpass_alert_success_sent" : "Password set confirmation sent",
    "forgotpass_alert_success_receive_mail1" : "You will receive an e-mail shortly containing a link that will allow you to set your password.",
    "forgotpass_alert_success_receive_mail2" : "When you receive this e-mail, please follow the link to complete your registration process.",
    "forgotpass_alert_success_reason_not_find_mail" : "There are a few reasons that you might not be able to find the activation email.",
    "forgotpass_alert_success_reason1" : "Please check the following things before you contact us:",
    "forgotpass_alert_success_reason2" : "Please always check your junk/spam folder.",
    "forgotpass_alert_success_reason3" : "Ensure your email id is correct.",
    "forgotpass_alert_success_reason4" : "Ensure your inbox is not full.",

    "register_sitedetail" : "Thank you for showing interest in Vikaspedia! Vikaspedia is a collaborative content creation portal. It allows moderated members to contribute content to the portal. You can register either as 'Member' or 'Content contributor', by clicking on the relevant item. The privileges for these roles are indicated below.",
    "register_member" : "Member",
    "register_member_feature1" : " Can view / discuss topics",
    "register_member_feature2" : " Can set preferences to view recent items",
    "register_member_feature3" : " Subscribe to online newsletter",
    "register_member_button" : "Member",

    "register_contributor" : "Content contributor",
    "register_contributor_feature1" : "Can edit pages",
    "register_contributor_feature2" : "Can add a new page",
    "register_contributor_feature3" : "Can create discussion topics",
    "register_contributor_button" : "Contributor",

    "register_member_pageheading" : "Member Registration",
    "register_member_note" : "Please Note:",
    "register_member_instruction1" : "Your email address will be your login name.",
    "register_member_instruction2" : "We respect your privacy, and will not share the address to any third party or expose it anywhere.",
    "register_member_instruction3" : "Using a single e-mail id , you can register only once in Vikaspedia portal.",
    "register_member_instruction4" : "Once the email id is used for registration in any of the language portals of Vikaspedia, the same cannot be used for further registration of any other role or in any other language portals.",
    "register_member_instruction5" : "Please enter valid email id which is being used by you on regular basis.",
    "register_member_full_name" : "Full Name",
    "register_member_full_name_" : "Full Name",
    "register_member_full_name_hint" : "Your name can include only alphabets (a to z), digits (0 to 9) and space. Characters like '.', ',','-', '_' are not allowed",
    "register_member_email" : "Email",
    "register_member_email_placeholder" : "Email/Username",
    "register_member_email_hint" : "Enter a email id. Your email id can contain , digits and character '_' . Your mail id must contain '@' symbol. Eg abck@kail.com",
    "register_member_email_required" : "Email Id is Required",
    "register_member_email_bad_format" : "Email format must be correct.",
    "register_member_password" : "Password",
    "register_member_password_placeholder" : "Password",
    "register_member_password_hint" : "Your password should contain a minimum of 8 characters. These can include alphabets ( a - z), digits (o - 9) and special characters (!,@,$,#,%,&).",
    "register_member_password_required" : "Password field is Required",
    "register_member_password_min_length" : "Password must contain 8 letters",
    "register_member_confirm_password" : "Confirm Password",
    "register_member_confirm_password_placeholder" : "Confirm Password",
    "register_member_confirm_password_hint" : "Re-enter the password. Make sure the passwords are identical.",
    "register_member_confirm_password_must_same" : "Password and confirm-password must be same",
    "register_member_subscribe_newsletter" : "Subscribe to newsletter ",
    "register_member_subscribe_newsletter_detail" : " If you want to unsubscribe (please uncheck the check box)",
    "register_member_accept_terms_conditions" : "I accept the terms and conditions ",
    "register_member_accept_terms_conditions_detail" : "By registering with this portal you acknowledge that you have read, understood and agree to the portal Terms and Conditions ",
    "register_member_submit_button" : "Submit",

    "register_contributor_pageheading" : "Contributor Registration",
    "register_contributor_note" : "Please Note:",
    "register_contributor_instruction1" : "Your email address will be your login name.",
    "register_contributor_instruction2" : "We respect your privacy, and will not share the address to any third party or expose it anywhere.",
    "register_contributor_instruction3" : "Using a single e-mail id , you can register only once in Vikaspedia portal.",
    "register_contributor_instruction4" : ".Once the email id is used for registration in any of the language portals of Vikaspedia, the same cannot be used for further registration of any other role or in any other language portals.",
    "register_contributor_instruction5" : "Please enter valid email id which is being used by you on regular basis.",
    
    "register_contributor_full_name" : "Full Name",
    "register_contributor_full_name_placeholder" : "Full Name",
    "register_contributor_full_name_hint" : "Your name can include only alphabets (a to z), digits (0 to 9) and space. Characters like '.', ',','-', '_' are not allowed.",
    
    "register_contributor_email" : "Email",
    "register_contributor_email_placeholder" : "Email/Username",
    "register_contributor_email_hint" : "Enter a email id. Your email id can contain , digits and character '_' . Your mail id must contain '@' symbol. Eg abck@kail.com",
    "register_contributor_email_required" : "Email Id is Required",
    "register_contributor_email_bad_format" : "Email format must be correct.",
    "register_contributor_password" : "Password",
    "register_contributor_password_placeholder" : "Password",
    "register_contributor_password_hint" : "Your password should contain a minimum of 8 characters. These can include alphabets ( a - z), digits (o - 9) and special characters (!,@,$,#,%,&).",
    "register_contributor_password_required" : "Password field is Required",
    "register_contributor_password_min_length" : "Password must contain 8 letters",
    "register_contributor_confirm_password" : "Confirm Password",
    "register_contributor_confirm_password_placeholder" : "Confirm Password",
    "register_contributor_confirm_password_hint" : "Re-enter the password. Make sure the passwords are identical.",
    "register_contributor_confirm_password_must_same" : "Password and confirm-password must be same",

    "register_contributor_phone" : "Phone",
    "register_contributor_phone_placeholder" : "Phone Number",
    "register_contributor_phone_invalid" : "Invalid Phone Number must contain 10 digit!",
    "register_contributor_age_group" : "Age Group",
    "register_contributor_age_group_selected" : "Not Selected",
    "register_contributor_Gender" : "Gender",
    "register_contributor_selected" : "Not Selected",
    "register_contributor_qualification" : "Qualification",
    "register_contributor_qualification_selected" : "Not Selected",
    "register_contributor_state" : "State",
    "register_contributor_state_selected" : "Not Selected",
    "register_contributor_district" : "District",
    "register_contributor_address" : "Address",
    "register_contributor_address_placeholder" : "Address",
    "register_contributor_postalcode" : "PostalCode",
    "register_contributor_postalcode_placeholder" : "Pin Code",
    "register_contributor_category" : "Category",
    "register_contributor_category_selected" : "Not Selected",
    "register_contributor_domain" : "Domain",
    "register_contributor_domain_instruction1" : "Domain In Which you wish to contribute in Vikaspedia",
    "register_contributor_domain_instruction2" : "You may select only two areas in which you have expertise. Your first choice will be considered as the first preference and the second choice as the second area of preference.",

    "register_contributor_domain_required" : "Domain cannot be empty. Please select....",

    "register_contributor_language" : "Language",
    "register_contributor_language_instruction1" : "Language In Which you wish to contribute in Vikaspedia you can select up to two language",
   
    "register_contributor_language_required" : "Language cannot be empty. Please select....",

    "register_contributor_experience" : "Experience(Years)",
    "register_contributor_experience_selected" : "Not Selected",

    "register_contributor_subscribe_newsletter" : "Subscribe to newsletter ",
    "register_contributor_subscribe_newsletter_detail" : " If you want to unsubscribe (please uncheck the check box)",
    "register_contributor_familiar_with_typing" : "I am familiar with typing in Indian language'(s) (Unicode)? ",
    "register_contributor_accept_terms_conditions" : "I accept the terms and conditions ",
    "register_contributor_accept_terms_conditions_detail" : "By registering with this portal you acknowledge that you have read, understood and agree to the portal Terms and Conditions ",
    "register_contributor_have_experience_in_contributing" : "I have experience in contributing online content ? ",
    "register_contributor_familiar_with_unicode" : "I am familiar with unicode and true type fonts? ",
    "register_contributor_submit_button" : "Register",



    "pageview_edit" : "Edit",
    "pageview_emply_folder" : "Emply folder.",
    "pageview_action" : "Action",
    "pageview_action_create_page" : "Create New Page",
    "pageview_action_create_folder" : "Create New Folder",
    "pageview_move" : "Move",
    
    
    "createpage_pageheading" : "Add Page",
    "createpage_title" : "Title",
    "createpage_title_placeholder" : "Page Title",
    "createpage_summery" : "Summery",
    "createpage_summery_placeholder" : "PageSummery",
    "createpage_content" : "Content",
    "createpage_change_note" : "Change note Enter a comment that describes the changes you made.",
    "createpage_change_note_placeholder" : "Change note",
    "createpage_submit_button" : "Submit",

    "fileupload_image" : "Image",
    "fileupload_select" : "Select",
    "fileupload_video" : "Video",
    "fileupload_file" : "File",
    "fileupload_upload_to_server" : "Upload to Server",
    "fileupload_embed_to_editor" : "Embed to Editor",

    "pageedit_pageheading" : "Edit Page",
    "pageedit_title" : "Title",
    "pageedit_title_placeholder" : "Page Title",
    "pageedit_summery" : "Summery",
    "pageedit_summery_placeholder" : "PageSummery",
    "pageedit_content" : "Content",
    "pageedit_change_note" : "Change note Enter a comment that describes the changes you made.",
    "pageedit_change_note_placeholder" : "Change note",
    "pageedit_save_button" : "Save",
    "pageedit_cancel_button" : "Cancel",


    "createfolder_pageheading" : "Add New Folder",
    "createfolder_title" : "Title",
    "createfolder_title_placeholder" : "Page Title",
    "createfolder_summery" : "Summery",
    "createfolder_summery_placeholder" : "PageSummery",
    "createfolder_image" : "Image",
    "createfolder_change_note" : "Change note Enter a comment that describes the changes you made.",
    "createfolder_change_note_placeholder" : "Change note",
    "createfolder_submit_button" : "Submit",

    "folderedit_pageheading" : "Add New Folder",
    "folderedit_title" : "Title",
    "folderedit_title_placeholder" : "Page Title",
    "folderedit_summery" : "Summery",
    "folderedit_summery_placeholder" : "PageSummery",
    "folderedit_image" : "Image",
    "folderedit_change_note" : "Change note Enter a comment that describes the changes you made.",
    "folderedit_change_note_placeholder" : "Change note",
    "folderedit_save_button" : "Save",
    "folderedit_cancel_button" : "Cancel",

    "resetpage_heading" : "Reset Your Password",
    "reset_alertheading" : "password updated successfully!",
    "reset_password"     : "Password",
    "reset_password_placeholder"     : "Password",
    "reset_password_required" : "Password field is Required",
    "reset_password_min_length" : "Password must contain 8 letters",
    "reset_confirmpassword"     : "Confirm Password",
    "reset_confirmpassword_placeholder"     : "Confirm Password",
    "reset_confirm_password_must_same" : "Password and confirm-password must be same",


    "commentadd_heading":"Post Your Suggestion",
    "comment_instruction":"(If you have any comments / suggestions on the above content, please post them here)",
    "comment_success":"Your comment has been posted successfully!",
    "comment_subhead":"Your Comment",
    "comment_add_submit_button":"Submit",
    "comment_add_placeholder":"comment here...",
    "commentget_heading": "Comments",
    "commentget_reply": "reply",
    "commentget_view": "view",
    "commentget_first": "First",
    "commentget_last": "Last",
    "commentget_submit": "submit",
    "commentget_replyhere": "reply here....",

    "rating_total_rating" : "ratings",
    "rating_total_comment" : "comments",
    "rating_yourrating" :"Your Rating",
    "rating_roolover":"Roll over stars then click to rate.",
    "rating_and" : "and",
    "rating_star1" : "Star1",
    "rating_star2" : "Star2",
    "rating_star3" : "Star3",
    "rating_star4" : "Star4",
    "rating_star5" : "Star5",
    "rating_review" : "Reviews",

    "terms_heading": "The multi-lingual portal,  www.vikaspedia.in,  is intended to provide as far as possible reliable information and data, mostly openly sourced. However C-DAC do not claim responsibility of authorship for any of the data, compiled from various sources, such as other web sites, and content consortiums. Effort is made to see that the content is as accurate as possible – where it is information based. Opinions and views expressed in articles, write-ups sourced from web sites and content partners on schemes, policies, etc, are not C-DAC’s  official views or opinions.",
    "terms_1":"C-DAC expressly disclaims all warranties and / or conditions, expressed or implied, as to any matter whatsoever relating to or referenced by the portal, including, but not limited to, the implied warranties and/or conditions of merchantability or satisfactory quality and fitness for a particular purpose and non infringement.",
    "terms_2":" In no event shall C-DAC be liable for any damages whatsoever (including, without limitation, damages for loss of profits, business interruption, loss of information) arising out of the use of or inability to use the materials, even if C-DAC has been advised of the possibility of such damages.",
    "terms_3":" C-DAC also does not warrant that the functions contained in the materials will be uninterrupted or error-free, or that defects will be corrected, or that this portal or the server that makes it available are free of viruses or other harmful components.",
    "terms_4":"That you understand and agree that any material downloaded or otherwise obtained through the use of the portal, is at your own discretion and risk and that you will be solely responsible for any damage to your computer system or loss of data that results from the download of materials.",
    "terms_5":"C-DAC does not give any warranty regarding any goods or services purchased or obtained through the portal or any transactions entered through the portal.",
    "terms_6":"Under no circumstances shall C-DAC be liable for any direct, indirect, incidental, punitive, special or consequential damages, resulting from:",
    "terms_6_1":"The use or the inability to use the portal.",
    "terms_6_2":"The cost of procurement of substitute goods and services resulting from any goods or services purchased or obtained or messages received or transactions entered in the portal.",
    "terms_6_3":"The materials in the portal.",
    "terms_6_4":"Any other matter related to the portal, even if C-DAC has been advised of the possibility of such damages.",
    "terms_footer1":"Because some jurisdictions prohibit the exclusion or limitation of liability for consequential or incidental damages, the above limitation may not apply to you",
    "terms_footer2":"C-DAC may provide access to C-DACs' international data and, therefore, may contain references or cross references to C-DAC products, programs and services that are not announced in your country. Such reference does not imply that C-DAC in your country intends to announce such products, programs or services.",

    "app": "English",
    "footer" : "Footer",
	"agri_data1": "Agri Inputs",
	"agri_data2": "Crop Production",
	"agri_data3": "post-harvest-technologies",
	"agri_data4": "Livestock",
	"agri_data5": "Poultry",

	"health_data1": "Women Health",
	"health_data2": "Child Health",
	"health_data3": "NRHM",
	"health_data4": "AYUSH",
	"health_data5": "Nutrition",

	"edu_data1": "Child rights",
	"edu_data2": "Policies/Schemes",
	"edu_data3": "Childrens Corner",
	"edu_data4": "Teachers Corner",
	"edu_data5": "online assessment",

	"social_data1": "Women and Child Development",
	"social_data2": "scheduled tribes welfare",
	"social_data3": "scheduled caste welfare",
	"social_data4": "backward classes",
	"social_data5": "unorganized sector",

	"energy_data1": "Energy Basics",
	"energy_data2": "energy conservation",
	"energy_data3": "Energy efficiency",
	"energy_data4": "energy production",
	"energy_data5": "Best Practices",

	"egov_data1": "e-Governance in india",
	"egov_data2": "About RTI Act 2005",
	"egov_data3": "e-Gov Services online",
	"egov_data4": "Resources for VLEs",
	"egov_data5": "Mobile Governance",

	"services_data1": "e-Vyapar",
	"services_data2": "Ask an Expert",
	"services_data3": "MOTHER",
	"services_data4": "Online Cources",
	"services_data5": "Reacaller",

	"agri_data1_url" : "/agriculture/agri-inputs",
	"agri_data2_url" : "/agriculture/crop-production",
	"agri_data3_url" : "/agriculture/post-harvest-technologies",
	"agri_data4_url" : "/agriculture/livestock",
	"agri_data5_url" : "/agriculture/poultry",
	"agri_see_more_url" : "/agriculture",

	"health_data1_url": "/health/women-health",
	"health_data2_url": "/health/child-health",
	"health_data3_url": "/health/nrhm",
	"health_data4_url": "/health/ayush",
	"health_data5_url": "/health/nutrition",
	"health_see_more_url": "/health",

	"edu_data1_url": "/education/child-rights",
	"edu_data2_url": "/education/policies-and-schemes",
	"edu_data3_url": "/education/childrens-corner",
	"edu_data4_url": "/education/teachers-corner",
	"edu_data5_url": "/education/online-assessment",
	"edu_see_more_url": "/education",

	"social_data1_url": "/social-welfare/women-and-child-development",
	"social_data2_url": "/social-welfare/scheduled-tribes-welfare",
	"social_data3_url": "/social-welfare/scheduled-caste-welfare-1",
	"social_data4_url": "/social-welfare/backward-classes-1",
	"social_data5_url": "/social-welfare/unorganised-sector-1/unorganized-sector-informal-sector",
	"social_see_more_url": "/social-welfare",

	"energy_data1_url": "/energy/energy-basics",
	"energy_data2_url": "/energy/energy-conservation",
	"energy_data3_url": "/energy/energy-efficiency",
	"energy_data4_url": "/energy/energy-production",
	"energy_data5_url": "/energy/best-practices",
	"energy_see_more_url": "/energy",

	"egov_data1_url": "/e-governance/national-e-governance-plan",
	"egov_data2_url": "/e-governance/about-rti-act-2005",
	"egov_data3_url": "/e-governance/online-citizen-services",
	"egov_data4_url": "/e-governance/resources-for-vles",
	"egov_data5_url": "/e-governance/mobile-governance",
	"egov_see_more_url" : "/e-governance",

	"portal_about_1":"This portal has been developed as part of the national level initiative - India Development Gateway (InDG), dedicated for providing information / knowledge and ICT based knowledge products and services in the domain of social development. InDG is a ",
	"portal_about_2" : " Government of India initiative and is executed by",
	"portal_about_3" : " ",
	"meity_text":"Ministry of Electronics and Information Technology (MeitY)",
	"cdac_text" : " Centre for Development of Advanced Computing, Hyderabad. ",
	"about_us":"About Us",
	"link_to_us":"Link to Us",
	"contact_us":"Contact Us",
	"help":"Help",
	"portal_policies":"Portal Policies",
	"add_to_favourite":"Add to Favourate",
	"give_your_feedback":"Give Your Feedback",
	"last_modified":"Last Modified ",
	"all_right_reserved":" © 2022 C-DAC. All rights reserved.",
	"sitemap" : "Site map",
	"home" : "Home",
	"share" : "Share",
	"last_modified_date": " April 19, 2022",
	"as_see_more": "See more",

	"tracking_progress": "TRACKING PROGRESS",
	"tracking_heading": "Composite Index",
	"tracking_index_score": "Index Score Value",
	"tracking_index_1": "Health and Nutrition",
	"tracking_index_2": "Education",
	"tracking_index_3": "Agriculture & Water Resources",
	"tracking_index_4": "Financial Inclusion & Skill Development",
	"tracking_index_5": "Basic Infrastructure"
  }  